// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-services.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var SERVICES = [
  {
    package: "Startup Website",
    price_gbp: { min: 400, max: 800 },
    description: "Unlimited pages, mobile-first responsive design, brand & design overhaul, 1 year managed hosting, basic SEO setup & analytics, domain configuration."
  },
  {
    package: "Custom Software",
    price_gbp: { min: 600, max: 2e3 },
    description: "Discovery & process mapping, custom dashboard/tool/automation, user auth & roles, integrations (Stripe, email, APIs), managed hosting & maintenance, team training & handover."
  }
];
var PROCESS = [
  "Discovery Call \u2014 understand business, users, process.",
  "Strategy & Wireframes \u2014 flows, data models, screens.",
  "Design \u2014 custom interface & brand, 2 review rounds.",
  "Build \u2014 modern hand-crafted code with auth, integrations, performance, accessibility.",
  "Launch & Support \u2014 deploy, train, ongoing hosting & maintenance."
];
var list_services_default = defineTool({
  name: "list_services_and_pricing",
  title: "List services & pricing",
  description: "Get Sadath Company's public studio packages, indicative GBP price ranges, and the studio process. Use to answer questions about what Sadath builds and what it costs.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify(
          {
            company: "The Sadath Company Ltd",
            location: "Cambridge, UK",
            contact_email: "contact@sadathcompany.com",
            note: "Indicative pricing only. Every engagement is scoped via a bespoke Statement of Work after a discovery call.",
            packages: SERVICES,
            process: PROCESS
          },
          null,
          2
        )
      }
    ],
    structuredContent: { packages: SERVICES, process: PROCESS }
  })
});

// src/lib/mcp/tools/submit-inquiry.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
var submit_inquiry_default = defineTool2({
  name: "submit_contact_inquiry",
  title: "Submit a contact inquiry",
  description: "File a new project inquiry with Sadath Company on behalf of a visitor. Captures name, email, optional company, the service they're interested in, and a description of their project. The Sadath team follows up by email within 24 hours.",
  inputSchema: {
    name: z.string().trim().min(1).max(100).describe("Full name of the person inquiring."),
    email: z.string().trim().email().max(255).describe("Contact email address."),
    company: z.string().trim().max(200).optional().describe("Company or project name (optional)."),
    service: z.enum([
      "Custom Software",
      "Booking or Scheduling System",
      "Startup Website",
      "E-Commerce / Custom Site",
      "Design Overhaul / Rebrand",
      "Consulting",
      "Other"
    ]).describe("Which service they're interested in."),
    description: z.string().trim().min(10).max(1e3).describe("Short description of the project, goals, and timeline.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ name, email, company, service, description }) => {
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_PUBLISHABLE_KEY;
    if (!url || !key) {
      return {
        content: [{ type: "text", text: "Server is not configured to accept inquiries." }],
        isError: true
      };
    }
    const supabase = createClient(url, key, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("submissions").insert({
      customer_name: name,
      customer_email: email,
      company_name: company ?? null,
      tier: service,
      description,
      status: "new_inquiry"
    }).select("id").single();
    if (error) {
      return {
        content: [{ type: "text", text: `Could not submit inquiry: ${error.message}` }],
        isError: true
      };
    }
    return {
      content: [
        {
          type: "text",
          text: `Inquiry received. The Sadath team will reply to ${email} within 24 hours. Reference: ${data.id}`
        }
      ],
      structuredContent: { id: data.id, status: "received" }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "sadath-company-mcp",
  title: "Sadath Company",
  version: "0.1.0",
  instructions: "Public MCP server for Sadath Company, a UK studio building custom business software and beautifully designed websites. Use `list_services_and_pricing` to answer questions about packages, price ranges, and the studio process. Use `submit_contact_inquiry` to file a new project lead on behalf of a visitor; the team follows up by email within 24 hours.",
  tools: [list_services_default, submit_inquiry_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
